package github.isyedaliraza.stacklite_backend;

import github.isyedaliraza.stacklite_backend.domain.entity.Answer;
import github.isyedaliraza.stacklite_backend.domain.entity.Question;
import github.isyedaliraza.stacklite_backend.domain.entity.Tag;
import github.isyedaliraza.stacklite_backend.domain.repository.AnswerRepository;
import github.isyedaliraza.stacklite_backend.domain.repository.QuestionRepository;
import github.isyedaliraza.stacklite_backend.domain.repository.TagRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.Arrays;

@SpringBootApplication
public class StackliteBackendApplication implements CommandLineRunner {
	private final TagRepository tagRepository;
	private final QuestionRepository questionRepository;
	private final AnswerRepository answerRepository;

    public StackliteBackendApplication(TagRepository tagRepository, QuestionRepository questionRepository,
                                       AnswerRepository answerRepository) {
        this.tagRepository = tagRepository;
        this.questionRepository = questionRepository;
        this.answerRepository = answerRepository;
    }

    public static void main(String[] args) {
		SpringApplication.run(StackliteBackendApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		// The following code is generated by ChatGPT as it is just a seed data for testing

		// Create tags
		Tag javaTag = new Tag();
		javaTag.setName("Java");
		Tag springTag = new Tag();
		springTag.setName("Spring");

		tagRepository.saveAll(Arrays.asList(javaTag, springTag));

		// Create questions
		Question q1 = new Question();
		q1.setTitle("How to use Spring Boot?");
		q1.setBody("I want to create a REST API with Spring Boot. How do I start?");
		q1.setTags(Arrays.asList(javaTag, springTag));

		Question q2 = new Question();
		q2.setTitle("Java Streams Example");
		q2.setBody("How do I use Streams in Java 17?");
		q2.setTags(Arrays.asList(javaTag));

		questionRepository.saveAll(Arrays.asList(q1, q2));

		// Create answers
		Answer a1 = new Answer();
		a1.setBody("You can start by creating a Spring Boot project with Spring Initializr.");
		a1.setQuestion(q1);

		Answer a2 = new Answer();
		a2.setBody("Use .stream() on your collection, then apply map/filter/collect.");
		a2.setQuestion(q2);

		answerRepository.saveAll(Arrays.asList(a1, a2));
	}
}
