spring:
  application:
    name: Stacklite Backend
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/stacklite
    driver-class-name: org.postgresql.Driver
    username: syedaliraza
    password: ""